### ISSUE TITLE
Invalid keyvals structure in custom logger

### ISSUE THREAD

**Issue by andig** [philippseith/signalr#139]
Sorry for asking here, but I couldn't figure it out. In https://github.com/evcc-io/evcc/issues/4290 I'm running into rare panics with a custom `signalr.StructuredLogger`. Root cause is that keyvals appear to have non-string type for key. The implementation is quite simple, basically converting keyvals into string:

```
func (l *logger) Log(keyVals ...interface{}) error {
	b := new(strings.Builder)

	var skip bool
	for i, v := range keyVals {
		if skip {
			skip = false
			continue
		}

		if i%2 == 0 {
			// don't log if key is not a string or if key should be skipped
			if slices.Contains(skipped, v.(string)) {
				skip = true
				continue
			}

			if b.Len() > 0 {
				b.WriteRune(' ')
			}

			b.WriteString(fmt.Sprintf("%v", v))
			b.WriteRune('=')
		} else {
			b.WriteString(fmt.Sprintf("%v", v))
		}
	}

	l.log.Println(b.String())

	return nil
}
```

What is confusing is the keyvals that triggers the panic:

    recovering from panic in logger: expected string, got []interface {} from 
    [ts 2022-09-02T07:58:24.050162127Z class Client connection jUObeOndRM7CWMG5x2KtCg hub charger.Easee ts 2022-09-02T07:58:24.050165252Z level info event message send message signalr.hubMessage{Type:6} error *signalr.webSocketConnection: failed to write msg: failed to write frame: WebSocket closed: received close frame: status = StatusNormalClosure and reason = ""]

It seems as if this is really two log messages intermingled in one:
- notice the duplicate timestamp
- notice the panic, it seems as if keyvals of one log message is used as key of another one (`[]interface {}` instead of `string`)

Any idea where that might be generated on signaler side?

**Comment by philippseith** [comment]
the logger  is created here: https://github.com/philippseith/signalr/blob/c9b8729b82897827acaba0e36ea086c036b1b716/client.go#L527
 The call which creates the log event is here:
https://github.com/philippseith/signalr/blob/c9b8729b82897827acaba0e36ea086c036b1b716/hubconnection.go#L254

All but one methods involved are from the `github.com/go-kit/log` package wich is used by more than 1000 packages (ok, not much for a logging package, but enough to exclude such an error (?))
The one involved from signalr (which also is logging `recovering from panic in logger...`) is https://github.com/philippseith/signalr/blob/c9b8729b82897827acaba0e36ea086c036b1b716/options.go#L113
this code seems to be ok.

What I don't get is: The only line in your code where something is cast to string is `if _, ok := v.(string); !ok || slices.Contains(skipped, v.(string)) {` where only the second cast could panic, but couldn't because `!ok` is true then.

**Comment by andig** [comment]
Thanks @philippseith for taking the time to respond. I'm really stuck here and no doubt the problem is not inside go-kit...

> What I don't get is: 

My bad. I've actually posted the code containing the current workaround, panicing version is this:

			if slices.Contains(skipped, v.(string)) {

Given the error above, would you have a hint what I could do to provoke the root error from somewhere within signaler so I could maybe get a traceable test case?

**Comment by philippseith** [comment]
You could use vendoring and hardcode an error in hubconnection.go before line 254

**Comment by andig** [comment]
Tried and get the error, but not the panic. I'm totally unable to repro it. I'll close here as the workaround takes care of it, if you should notice something odd with the logging later on feel free to leave a note here. Thank you!
